name = "AthlynxFrontend"
uuid = "12345678-1234-5678-1234-567812345678"
authors = ["Chad A. Dozier <cdozier14@dozierholdingsgroup.com.mx>"]
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Stripe = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.9"
HTTP = "1"
Genie = "5"
JSON3 = "1"
