name = "AthlynxFrontend"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Chad A. Dozier <cdozier14@dozierholdingsgroup.com.mx>"]
version = "1.0.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6b3"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
HTTP = "^1.10"
Genie = "^5.30"
JSON = "^0.21"
julia = "^1.9"
